global:
  namespace: voting-app

ingress:
  enabled: true
  className: nginx

  voteHost: vote.local
  resultHost: result.local

postgresql:
  enabled: true

  image:
    registry: docker.io
    repository: postgres
    tag: "17"

  auth:
    username: postgres
    password: postgres
    database: postgres

redis:
  enabled: true

  image:
    registry: docker.io
    repository: redis
    tag: "7.4"

postgresql:
  enabled: true

  image:
    registry: docker.io
    repository: postgres
    tag: "17"

  auth:
    username: postgres
    password: postgres
    database: postgres

  primary:
    containerSecurityContext:
      enabled: false

    podSecurityContext:
      enabled: false

redis:
  architecture: standalone


redis:
  architecture: standalone

  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: "8.2.1-debian-12-r0"

