apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "vote.fullname" . }}
  labels:
    {{- include "vote.labels" . | nindent 4 }}

data:
  OPTION_A: {{ .Values.config.optionA | quote }}
  OPTION_B: {{ .Values.config.optionB | quote }}
