apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "vote.fullname" . }}
  labels:
    {{- include "vote.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "vote.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "vote.selectorLabels" . | nindent 8 }}

    spec:
      containers:
      - name: vote
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 80

        env:

        - name: OPTION_A
          valueFrom:
            configMapKeyRef:
              name: {{ include "vote.fullname" . }}
              key: OPTION_A

        - name: OPTION_B
          valueFrom:
            configMapKeyRef:
              name: {{ include "vote.fullname" . }}
              key: OPTION_B

        - name: REDIS_HOST
          value: voting-app-redis-master

        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-redis
              key: redis-password
